config/routes.rb
Rails.application.routes.draw do
  get 'people/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParsingTextApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<h1 class='text-center'> My Fav Peeps List </h1>

<%= render partial: "shared/table", locals: {people: @people} %>

<%= link_to "Go Back to Reality" , root_path, class: 'btn btn-danger'%>

 

app/views/shared/_table.html.erb
<div class="container">

<table  class="table"  >
  <thead>
    <tr>
       <th scope="col" >#</th>
     <th scope="col" >First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col" >Favorite Color </th>
    </tr>
  </thead>
  <tbody>
  
<% people.each do |p|%>
    <tr>
        <td><%= p.id%></td>
        <td><%= p.first_name%></td>
        <td><%= p.last_name%></td>
        <td><%= p.fav_color%></td>
    </tr>
<%end%>
  </tbody>
</table>

</div>

app/views/welcome/index.html.erb
 <%= link_to "My Fav Peeps" , people_index_path , class: 'btn btn-primary'%>